[tool.poetry]
name = "vqcpc"
version = "0.1.0"
description = "Reimplementation of VQ-CPC with PyTorch"
authors = ["Tarepan"]
readme = "README.md"
repository = "https://github.com/tarepan/VectorQuantizedCPC"

[tool.poetry.dependencies]
python = "^3.7"
torch = "*"
# torchaudio = "^0.9.0"
# pytorch-lightning = "^1.4.9"
# fsspec = {version = ">=2021.5", extras = ["http", "s3"]}
# boto3 = "^1.16.18"
numpy = ">=1.17"
scipy>=1.4
librosa = "^0.8.0"
# corpuspy = {git = "https://github.com/tarepan/corpuspy.git", rev = "main"}
rnnms = {git = "https://github.com/tarepan/UniversalVocoding.git", rev = "main"}
pyloudnorm = "^0.1.0"
omegaconf = "^2.1.1"
tqdm>=4.45.0

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"